### ISSUE TITLE
Cannot find products

### ISSUE THREAD

**Issue by R4vio** [rkalis/AppiePy#15]
Running the code provided in the example gives an ProductNotFoundException
```
from functions import Product
import json
product = Product('https://www.ah.nl/producten/product/wi193679/lay-s-paprika')
print(json.dumps(product.__dict__, indent=4, sort_keys=True))
```
```
<Response [404]>
Traceback (most recent call last):
  File "c:\Users\Amin\Documents\VSCode\Random Projects\SupermarktStuff\main.py", line 3, in <module>
    product = Product('https://www.ah.nl/producten/product/wi193679/lay-s-paprika')
  File "c:\Users\Amin\Documents\VSCode\Random Projects\SupermarktStuff\functions.py", line 52, in __init__
    raise ProductNotFoundException(url)
functions.ProductNotFoundException: Product with URL https://www.ah.nl/producten/product/wi193679/lay-s-paprika could not be found
```

**Comment by rkalis** [comment]
It appears that Albert Heijn changed their internal API that AppiePy was relying on. I'll happily merge any PRs that figure out the new API and update the code.

**Comment by rkalis** [comment]
It looks like the old internal API is completely removed, so I'll be marking AppiePy as defunct and archive the repository. The code will stay online for anyone to clone if they figure out how to make it work again.
